/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuienSoyRouteImport } from './routes/quien-soy'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BitacoraIndexRouteImport } from './routes/bitacora.index'
import { Route as BitacoraRutasGpxRouteImport } from './routes/bitacora.rutas-gpx'
import { Route as BitacoraVideosIndexRouteImport } from './routes/bitacora.videos.index'
import { Route as BitacoraMedallasIndexRouteImport } from './routes/bitacora.medallas.index'
import { Route as BitacoraFotografiasIndexRouteImport } from './routes/bitacora.fotografias.index'
import { Route as BitacoraCuadernosDocumentosIndexRouteImport } from './routes/bitacora.cuadernos-documentos.index'
import { Route as BitacoraAudiosIndexRouteImport } from './routes/bitacora.audios.index'
import { Route as BitacoraVideosSlugRouteImport } from './routes/bitacora.videos.$slug'
import { Route as BitacoraMedallasSlugRouteImport } from './routes/bitacora.medallas.$slug'
import { Route as BitacoraFotografiasSlugRouteImport } from './routes/bitacora.fotografias.$slug'
import { Route as BitacoraCuadernosDocumentosSlugRouteImport } from './routes/bitacora.cuadernos-documentos.$slug'
import { Route as BitacoraAudiosSlugRouteImport } from './routes/bitacora.audios.$slug'

const QuienSoyRoute = QuienSoyRouteImport.update({
  id: '/quien-soy',
  path: '/quien-soy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraIndexRoute = BitacoraIndexRouteImport.update({
  id: '/bitacora/',
  path: '/bitacora/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraRutasGpxRoute = BitacoraRutasGpxRouteImport.update({
  id: '/bitacora/rutas-gpx',
  path: '/bitacora/rutas-gpx',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraVideosIndexRoute = BitacoraVideosIndexRouteImport.update({
  id: '/bitacora/videos/',
  path: '/bitacora/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraMedallasIndexRoute = BitacoraMedallasIndexRouteImport.update({
  id: '/bitacora/medallas/',
  path: '/bitacora/medallas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraFotografiasIndexRoute =
  BitacoraFotografiasIndexRouteImport.update({
    id: '/bitacora/fotografias/',
    path: '/bitacora/fotografias/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BitacoraCuadernosDocumentosIndexRoute =
  BitacoraCuadernosDocumentosIndexRouteImport.update({
    id: '/bitacora/cuadernos-documentos/',
    path: '/bitacora/cuadernos-documentos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BitacoraAudiosIndexRoute = BitacoraAudiosIndexRouteImport.update({
  id: '/bitacora/audios/',
  path: '/bitacora/audios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraVideosSlugRoute = BitacoraVideosSlugRouteImport.update({
  id: '/bitacora/videos/$slug',
  path: '/bitacora/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraMedallasSlugRoute = BitacoraMedallasSlugRouteImport.update({
  id: '/bitacora/medallas/$slug',
  path: '/bitacora/medallas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraFotografiasSlugRoute = BitacoraFotografiasSlugRouteImport.update({
  id: '/bitacora/fotografias/$slug',
  path: '/bitacora/fotografias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BitacoraCuadernosDocumentosSlugRoute =
  BitacoraCuadernosDocumentosSlugRouteImport.update({
    id: '/bitacora/cuadernos-documentos/$slug',
    path: '/bitacora/cuadernos-documentos/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const BitacoraAudiosSlugRoute = BitacoraAudiosSlugRouteImport.update({
  id: '/bitacora/audios/$slug',
  path: '/bitacora/audios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRoute
  '/historias': typeof HistoriasRoute
  '/quien-soy': typeof QuienSoyRoute
  '/bitacora/rutas-gpx': typeof BitacoraRutasGpxRoute
  '/bitacora/': typeof BitacoraIndexRoute
  '/bitacora/audios/$slug': typeof BitacoraAudiosSlugRoute
  '/bitacora/cuadernos-documentos/$slug': typeof BitacoraCuadernosDocumentosSlugRoute
  '/bitacora/fotografias/$slug': typeof BitacoraFotografiasSlugRoute
  '/bitacora/medallas/$slug': typeof BitacoraMedallasSlugRoute
  '/bitacora/videos/$slug': typeof BitacoraVideosSlugRoute
  '/bitacora/audios/': typeof BitacoraAudiosIndexRoute
  '/bitacora/cuadernos-documentos/': typeof BitacoraCuadernosDocumentosIndexRoute
  '/bitacora/fotografias/': typeof BitacoraFotografiasIndexRoute
  '/bitacora/medallas/': typeof BitacoraMedallasIndexRoute
  '/bitacora/videos/': typeof BitacoraVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRoute
  '/historias': typeof HistoriasRoute
  '/quien-soy': typeof QuienSoyRoute
  '/bitacora/rutas-gpx': typeof BitacoraRutasGpxRoute
  '/bitacora': typeof BitacoraIndexRoute
  '/bitacora/audios/$slug': typeof BitacoraAudiosSlugRoute
  '/bitacora/cuadernos-documentos/$slug': typeof BitacoraCuadernosDocumentosSlugRoute
  '/bitacora/fotografias/$slug': typeof BitacoraFotografiasSlugRoute
  '/bitacora/medallas/$slug': typeof BitacoraMedallasSlugRoute
  '/bitacora/videos/$slug': typeof BitacoraVideosSlugRoute
  '/bitacora/audios': typeof BitacoraAudiosIndexRoute
  '/bitacora/cuadernos-documentos': typeof BitacoraCuadernosDocumentosIndexRoute
  '/bitacora/fotografias': typeof BitacoraFotografiasIndexRoute
  '/bitacora/medallas': typeof BitacoraMedallasIndexRoute
  '/bitacora/videos': typeof BitacoraVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreras': typeof CarrerasRoute
  '/historias': typeof HistoriasRoute
  '/quien-soy': typeof QuienSoyRoute
  '/bitacora/rutas-gpx': typeof BitacoraRutasGpxRoute
  '/bitacora/': typeof BitacoraIndexRoute
  '/bitacora/audios/$slug': typeof BitacoraAudiosSlugRoute
  '/bitacora/cuadernos-documentos/$slug': typeof BitacoraCuadernosDocumentosSlugRoute
  '/bitacora/fotografias/$slug': typeof BitacoraFotografiasSlugRoute
  '/bitacora/medallas/$slug': typeof BitacoraMedallasSlugRoute
  '/bitacora/videos/$slug': typeof BitacoraVideosSlugRoute
  '/bitacora/audios/': typeof BitacoraAudiosIndexRoute
  '/bitacora/cuadernos-documentos/': typeof BitacoraCuadernosDocumentosIndexRoute
  '/bitacora/fotografias/': typeof BitacoraFotografiasIndexRoute
  '/bitacora/medallas/': typeof BitacoraMedallasIndexRoute
  '/bitacora/videos/': typeof BitacoraVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreras'
    | '/historias'
    | '/quien-soy'
    | '/bitacora/rutas-gpx'
    | '/bitacora/'
    | '/bitacora/audios/$slug'
    | '/bitacora/cuadernos-documentos/$slug'
    | '/bitacora/fotografias/$slug'
    | '/bitacora/medallas/$slug'
    | '/bitacora/videos/$slug'
    | '/bitacora/audios/'
    | '/bitacora/cuadernos-documentos/'
    | '/bitacora/fotografias/'
    | '/bitacora/medallas/'
    | '/bitacora/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreras'
    | '/historias'
    | '/quien-soy'
    | '/bitacora/rutas-gpx'
    | '/bitacora'
    | '/bitacora/audios/$slug'
    | '/bitacora/cuadernos-documentos/$slug'
    | '/bitacora/fotografias/$slug'
    | '/bitacora/medallas/$slug'
    | '/bitacora/videos/$slug'
    | '/bitacora/audios'
    | '/bitacora/cuadernos-documentos'
    | '/bitacora/fotografias'
    | '/bitacora/medallas'
    | '/bitacora/videos'
  id:
    | '__root__'
    | '/'
    | '/carreras'
    | '/historias'
    | '/quien-soy'
    | '/bitacora/rutas-gpx'
    | '/bitacora/'
    | '/bitacora/audios/$slug'
    | '/bitacora/cuadernos-documentos/$slug'
    | '/bitacora/fotografias/$slug'
    | '/bitacora/medallas/$slug'
    | '/bitacora/videos/$slug'
    | '/bitacora/audios/'
    | '/bitacora/cuadernos-documentos/'
    | '/bitacora/fotografias/'
    | '/bitacora/medallas/'
    | '/bitacora/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrerasRoute: typeof CarrerasRoute
  HistoriasRoute: typeof HistoriasRoute
  QuienSoyRoute: typeof QuienSoyRoute
  BitacoraRutasGpxRoute: typeof BitacoraRutasGpxRoute
  BitacoraIndexRoute: typeof BitacoraIndexRoute
  BitacoraAudiosSlugRoute: typeof BitacoraAudiosSlugRoute
  BitacoraCuadernosDocumentosSlugRoute: typeof BitacoraCuadernosDocumentosSlugRoute
  BitacoraFotografiasSlugRoute: typeof BitacoraFotografiasSlugRoute
  BitacoraMedallasSlugRoute: typeof BitacoraMedallasSlugRoute
  BitacoraVideosSlugRoute: typeof BitacoraVideosSlugRoute
  BitacoraAudiosIndexRoute: typeof BitacoraAudiosIndexRoute
  BitacoraCuadernosDocumentosIndexRoute: typeof BitacoraCuadernosDocumentosIndexRoute
  BitacoraFotografiasIndexRoute: typeof BitacoraFotografiasIndexRoute
  BitacoraMedallasIndexRoute: typeof BitacoraMedallasIndexRoute
  BitacoraVideosIndexRoute: typeof BitacoraVideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quien-soy': {
      id: '/quien-soy'
      path: '/quien-soy'
      fullPath: '/quien-soy'
      preLoaderRoute: typeof QuienSoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/': {
      id: '/bitacora/'
      path: '/bitacora'
      fullPath: '/bitacora/'
      preLoaderRoute: typeof BitacoraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/rutas-gpx': {
      id: '/bitacora/rutas-gpx'
      path: '/bitacora/rutas-gpx'
      fullPath: '/bitacora/rutas-gpx'
      preLoaderRoute: typeof BitacoraRutasGpxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/videos/': {
      id: '/bitacora/videos/'
      path: '/bitacora/videos'
      fullPath: '/bitacora/videos/'
      preLoaderRoute: typeof BitacoraVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/medallas/': {
      id: '/bitacora/medallas/'
      path: '/bitacora/medallas'
      fullPath: '/bitacora/medallas/'
      preLoaderRoute: typeof BitacoraMedallasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/fotografias/': {
      id: '/bitacora/fotografias/'
      path: '/bitacora/fotografias'
      fullPath: '/bitacora/fotografias/'
      preLoaderRoute: typeof BitacoraFotografiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/cuadernos-documentos/': {
      id: '/bitacora/cuadernos-documentos/'
      path: '/bitacora/cuadernos-documentos'
      fullPath: '/bitacora/cuadernos-documentos/'
      preLoaderRoute: typeof BitacoraCuadernosDocumentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/audios/': {
      id: '/bitacora/audios/'
      path: '/bitacora/audios'
      fullPath: '/bitacora/audios/'
      preLoaderRoute: typeof BitacoraAudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/videos/$slug': {
      id: '/bitacora/videos/$slug'
      path: '/bitacora/videos/$slug'
      fullPath: '/bitacora/videos/$slug'
      preLoaderRoute: typeof BitacoraVideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/medallas/$slug': {
      id: '/bitacora/medallas/$slug'
      path: '/bitacora/medallas/$slug'
      fullPath: '/bitacora/medallas/$slug'
      preLoaderRoute: typeof BitacoraMedallasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/fotografias/$slug': {
      id: '/bitacora/fotografias/$slug'
      path: '/bitacora/fotografias/$slug'
      fullPath: '/bitacora/fotografias/$slug'
      preLoaderRoute: typeof BitacoraFotografiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/cuadernos-documentos/$slug': {
      id: '/bitacora/cuadernos-documentos/$slug'
      path: '/bitacora/cuadernos-documentos/$slug'
      fullPath: '/bitacora/cuadernos-documentos/$slug'
      preLoaderRoute: typeof BitacoraCuadernosDocumentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitacora/audios/$slug': {
      id: '/bitacora/audios/$slug'
      path: '/bitacora/audios/$slug'
      fullPath: '/bitacora/audios/$slug'
      preLoaderRoute: typeof BitacoraAudiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrerasRoute: CarrerasRoute,
  HistoriasRoute: HistoriasRoute,
  QuienSoyRoute: QuienSoyRoute,
  BitacoraRutasGpxRoute: BitacoraRutasGpxRoute,
  BitacoraIndexRoute: BitacoraIndexRoute,
  BitacoraAudiosSlugRoute: BitacoraAudiosSlugRoute,
  BitacoraCuadernosDocumentosSlugRoute: BitacoraCuadernosDocumentosSlugRoute,
  BitacoraFotografiasSlugRoute: BitacoraFotografiasSlugRoute,
  BitacoraMedallasSlugRoute: BitacoraMedallasSlugRoute,
  BitacoraVideosSlugRoute: BitacoraVideosSlugRoute,
  BitacoraAudiosIndexRoute: BitacoraAudiosIndexRoute,
  BitacoraCuadernosDocumentosIndexRoute: BitacoraCuadernosDocumentosIndexRoute,
  BitacoraFotografiasIndexRoute: BitacoraFotografiasIndexRoute,
  BitacoraMedallasIndexRoute: BitacoraMedallasIndexRoute,
  BitacoraVideosIndexRoute: BitacoraVideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
